"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { api, allPages, errorMessage } from "@/lib/api";
import type { CounselorProgress, CounselorPlanItemProgress } from "@/lib/counselorProgress";
import type { DailyReport } from "@/lib/dailyReports";
import { minutesText, reportStatus } from "@/lib/dailyReports";
import { Commitment, commitmentLabel, kindLabel, persianDate, Plan, Student, timeText } from "@/lib/planning";
import type { ReportMetric, ReportResponse } from "@/lib/reports";
import { daysAgoIso, tehranTodayIso } from "@/lib/reports";
import { useCounselor } from "@/lib/counselorContext";
import { PlannedActualChart, ReportInsights, ReportSummary, SubjectDistribution, TrendChart } from "@/components/ReportVisuals";

type Tab = "overview" | "plans" | "reports" | "progress" | "profile";
const tabs: { id: Tab; label: string }[] = [{ id: "overview", label: "نمای کلی" }, { id: "plans", label: "برنامه‌ها" }, { id: "reports", label: "گزارش‌ها" }, { id: "progress", label: "پیشرفت" }, { id: "profile", label: "مشخصات" }];
const statusLabel: Record<CounselorPlanItemProgress["status"], string> = { NOT_STARTED: "شروع نشده", IN_PROGRESS: "در حال انجام", PAUSED: "متوقف شده", COMPLETED: "انجام‌شده", PARTIAL: "ناقص", NOT_DONE: "انجام‌نشده" };

function ItemRow({ item }: { item: CounselorPlanItemProgress }) {
  const title = [item.subject || item.title || kindLabel[item.kind], item.chapter, item.topic].filter(Boolean).join(" — ");
  return <article className="workspace-item"><div><span className="planning-badge">{kindLabel[item.kind]}</span><strong>{title}</strong><span className={`workspace-state state-${item.status.toLowerCase()}`}>{statusLabel[item.status]}</span></div><div className="workspace-comparison"><span><small>برنامه مشاور</small>{item.planned_minutes === null ? "—" : minutesText(item.planned_minutes)}{item.planned_tests !== null && ` · ${item.planned_tests} تست`}</span><span><small>عملکرد دانش‌آموز</small>{item.actual_minutes === null ? "ثبت نشده" : minutesText(item.actual_minutes)}{item.actual_tests !== null && ` · ${item.actual_tests} تست`}</span></div></article>;
}

function Overview({ id, progress, currentPlan }: { id: string; progress: CounselorProgress; currentPlan?: Plan }) {
  const today = progress.today; const items = progress.planned_items.filter((item) => item.date === today.date); const remaining = items.filter((item) => item.status !== "COMPLETED");
  return <div className="workspace-stack"><section className="workspace-panel workspace-today"><div className="workspace-section-title"><div><p className="workspace-eyebrow">امروز</p><h2>{persianDate(today.date)}</h2></div>{currentPlan && <Link href={`/counselor/students/${id}/planning?plan=${currentPlan.id}`}>مشاهده برنامه جاری</Link>}</div><div className="workspace-metrics"><div><small>برنامه مشاور</small><strong>{minutesText(today.planned_minutes)}</strong></div><div><small>عملکرد دانش‌آموز</small><strong>{minutesText(today.actual_minutes)}</strong></div><div><small>باکس‌ها</small><strong>{today.completed} از {today.planned_blocks}</strong></div><div><small>تست</small><strong>{today.actual_tests} از {today.planned_tests}</strong></div></div><div className="workspace-alerts">{today.partial > 0 && <span>{today.partial} باکس ناقص</span>}{today.not_done > 0 && <span>{today.not_done} باکس انجام‌نشده</span>}{!today.has_report && <span>گزارش امروز تکمیل نشده</span>}</div></section>
    <section className="workspace-panel"><div className="workspace-section-title"><h2>برنامه امروز</h2>{currentPlan && <Link href={`/counselor/students/${id}/planning?plan=${currentPlan.id}`}>{currentPlan.status === "DRAFT" ? "ویرایش برنامه" : "مشاهده برنامه"}</Link>}</div>{items.length ? <div className="workspace-list">{items.map((item) => <ItemRow item={item} key={item.id}/>)}</div> : <div className="workspace-empty"><p>برای امروز باکسی در برنامه منتشرشده ثبت نشده است.</p><Link className="planning-primary" href={`/counselor/students/${id}/planning?new=1`}>نوشتن برنامه جدید</Link></div>}</section>
    {remaining.length > 0 && <section className="workspace-panel"><h2>کارهای باقی‌مانده امروز</h2><div className="workspace-list compact">{remaining.map((item) => { const left = Math.max(0, (item.planned_minutes || 0) - (item.actual_minutes || 0)); return <div key={item.id}><strong>{item.subject || item.title || kindLabel[item.kind]}</strong><span>{item.status === "NOT_DONE" ? "انجام نشده" : item.kind === "TEST" && item.planned_tests ? `${item.actual_tests || 0} از ${item.planned_tests} تست` : left ? `${minutesText(left)} باقی مانده` : statusLabel[item.status]}</span></div>; })}</div></section>}
    <section className="workspace-panel workspace-quick"><h2>اقدام‌های سریع</h2><div><Link className="planning-primary" href={`/counselor/students/${id}/planning?new=1`}>+ نوشتن برنامه جدید</Link>{currentPlan && <Link href={`/counselor/students/${id}/planning?plan=${currentPlan.id}`}>مشاهده برنامه جاری</Link>}<button type="button" onClick={() => document.querySelector<HTMLButtonElement>('[data-tab="reports"]')?.click()}>گزارش امروز و همه گزارش‌ها</button></div></section></div>;
}

function PlansTab({ id, plans, progress, token, reload }: { id: string; plans: Plan[]; progress: CounselorProgress; token: string; reload: () => Promise<void> }) {
  const router = useRouter(); const [busy, setBusy] = useState<number | null>(null); const [error, setError] = useState(""); const today = tehranTodayIso(); const current = plans.find((p) => p.status === "PUBLISHED" && p.start_date <= today && p.end_date >= today);
  async function duplicate(plan: Plan) { setBusy(plan.id); setError(""); try { const copy = await api<Plan>(`/planning/plans/${plan.id}/duplicate/`, token, "POST", {}); await reload(); router.push(`/counselor/students/${id}/planning?plan=${copy.id}`); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(null); } }
  const groups = [{ label: "برنامه جاری", rows: current ? [current] : [] }, { label: "پیش‌نویس‌ها", rows: plans.filter((p) => p.status === "DRAFT") }, { label: "برنامه‌های قبلی", rows: plans.filter((p) => p.status === "PUBLISHED" && p.id !== current?.id) }];
  return <div className="workspace-stack"><p className="planning-error">{error}</p>{groups.map((group) => <section className="workspace-panel" key={group.label}><h2>{group.label}</h2>{group.rows.length ? <div className="workspace-plan-list">{group.rows.map((plan) => { const items = progress.planned_items.filter((item) => item.date >= plan.start_date && item.date <= plan.end_date); const planned = items.reduce((sum, item) => sum + (item.planned_minutes || 0), 0); const actual = items.reduce((sum, item) => sum + (item.actual_minutes || 0), 0); const completed = items.filter((item) => item.status === "COMPLETED").length; return <article key={plan.id}><div><h3>{plan.title || `${persianDate(plan.start_date)} تا ${persianDate(plan.end_date)}`}</h3><span className={`planning-status ${plan.status === "PUBLISHED" ? "is-published" : ""}`}>{plan.status === "DRAFT" ? "پیش‌نویس" : "منتشرشده"}</span></div><p>{persianDate(plan.start_date)} تا {persianDate(plan.end_date)}</p>{items.length > 0 && <div className="workspace-comparison"><span><small>برنامه مشاور</small>{minutesText(planned)}</span><span><small>عملکرد دانش‌آموز</small>{minutesText(actual)} · {Math.round(completed * 100 / items.length)}٪ اجرا</span></div>}<div className="workspace-actions"><Link href={`/counselor/students/${id}/planning?plan=${plan.id}`}>{plan.status === "DRAFT" ? "ویرایش برنامه" : "مشاهده برنامه"}</Link><button disabled={busy === plan.id} onClick={() => duplicate(plan)}>ساخت از روی برنامه قبلی</button></div></article>; })}</div> : <p className="workspace-empty-text">موردی در این بخش وجود ندارد.</p>}</section>)}</div>;
}

function ReportsTab({ id, token }: { id: string; token: string }) {
  const today = tehranTodayIso(); const [days, setDays] = useState(7); const [custom, setCustom] = useState(false); const [customStart, setCustomStart] = useState(daysAgoIso(today, 6)); const [customEnd, setCustomEnd] = useState(today); const [range, setRange] = useState({ start: daysAgoIso(today, 6), end: today }); const [metric, setMetric] = useState<ReportMetric>("all"); const [report, setReport] = useState<ReportResponse | null>(null); const [history, setHistory] = useState<{id:number;date:string;self_rating:number|null}[]>([]); const [detail, setDetail] = useState<DailyReport | null>(null); const [error, setError] = useState("");
  useEffect(() => { Promise.all([api<ReportResponse>(`/counselor/students/${id}/reports/?start_date=${range.start}&end_date=${range.end}&metric=${metric}`, token), allPages<{id:number;date:string;self_rating:number|null}>(`/daily-reports/?student=${id}`, token)]).then(([summary, rows]) => { setReport(summary); setHistory(rows.filter((row) => row.date >= range.start && row.date <= range.end)); }).catch(() => { setReport(null); setError("دریافت اطلاعات گزارش با مشکل مواجه شد."); }); }, [id, metric, range, token]);
  async function openDay(reportId: number) { try { setDetail(await api<DailyReport>(`/daily-reports/${reportId}/`, token)); } catch (reason) { setError(errorMessage(reason)); } }
  return <div className="workspace-stack"><section className="workspace-panel workspace-filters"><div>{([[1,"امروز"],[7,"۷ روز گذشته"],[30,"۳۰ روز گذشته"]] as const).map(([value,label]) => <button className={!custom && days === value ? "is-active" : ""} key={value} onClick={() => { setDays(value); setCustom(false); setRange({ start: daysAgoIso(today, value - 1), end: today }); }}>{label}</button>)}<button className={custom ? "is-active" : ""} onClick={() => setCustom(true)}>بازه دلخواه</button></div><select value={metric} onChange={(event) => setMetric(event.target.value as ReportMetric)}><option value="all">همه</option><option value="study">مطالعه</option><option value="tests">تست</option><option value="plan">اجرای برنامه</option></select>{custom && <form className="planning-form-row" onSubmit={(event) => { event.preventDefault(); if (customStart > customEnd) { setError("تاریخ شروع باید پیش از تاریخ پایان باشد."); return; } setError(""); setRange({ start: customStart, end: customEnd }); }}><label>از تاریخ<input type="date" value={customStart} max={today} onChange={(event) => setCustomStart(event.target.value)}/></label><label>تا تاریخ<input type="date" value={customEnd} max={today} onChange={(event) => setCustomEnd(event.target.value)}/></label><button>نمایش گزارش</button></form>}</section><p className="planning-error">{error}</p>{report && <><div className="report-page-header"><p>بازه گزارش: {persianDate(report.start_date)} تا {persianDate(report.end_date)}</p></div><ReportSummary report={report} audience="counselor"/><TrendChart report={report}/><PlannedActualChart report={report}/><SubjectDistribution report={report}/><ReportInsights report={report}/></>}
    <section className="workspace-panel"><h2>تاریخچه روزانه</h2>{history.length ? <div className="workspace-history">{history.map((row) => <button key={row.id} onClick={() => openDay(row.id)}><span><strong>{persianDate(row.date)}</strong>{row.self_rating !== null && <small>نمره روز: {row.self_rating}/۲۰</small>}</span><span>مشاهده جزئیات ←</span></button>)}</div> : <p className="workspace-empty-text">هنوز گزارشی از این دانش‌آموز ثبت نشده است.</p>}</section>{detail && <section className="workspace-panel"><div className="workspace-section-title"><h2>گزارش {persianDate(detail.date)}</h2><button onClick={() => setDetail(null)}>بستن</button></div><div className="workspace-metrics"><div><small>عملکرد دانش‌آموز</small><strong>{minutesText(detail.summary.total_actual_minutes)}</strong></div><div><small>تست واقعی</small><strong>{detail.summary.total_tests}</strong></div><div><small>انجام‌شده</small><strong>{detail.summary.completed_plan_items}</strong></div><div><small>ناقص / انجام‌نشده</small><strong>{detail.summary.partial_plan_items} / {detail.summary.not_done_plan_items}</strong></div></div>{detail.closed_at && <div className="workspace-reflection"><strong>نمره‌ای که دانش‌آموز به روزش داده: {detail.self_rating}/۲۰</strong><p>دلیل: «{detail.note}»</p></div>}<div className="workspace-list">{detail.items.map((item) => <article className="workspace-item" key={item.id}><div><strong>{item.subject_name || item.title || kindLabel[item.kind]}</strong><span className="workspace-state">{reportStatus[item.execution_status]}</span></div><div className="workspace-comparison"><span><small>برنامه مشاور</small>{item.planned_duration_minutes === null ? "خارج از برنامه" : minutesText(item.planned_duration_minutes)}{item.planned_test_count !== null && ` · ${item.planned_test_count} تست`}</span><span><small>عملکرد دانش‌آموز</small>{item.actual_duration_minutes === null ? "ثبت نشده" : minutesText(item.actual_duration_minutes)}{item.actual_test_count !== null && ` · ${item.actual_test_count} تست`}</span></div></article>)}</div></section>}</div>;
}

function ProgressTab({ progress }: { progress: CounselorProgress }) {
  return <div className="workspace-stack"><section className="workspace-panel"><h2>روند مطالعه ۷ روز اخیر</h2><div className="workspace-trend">{[...progress.recent_days].reverse().map((day) => <div key={day.date}><b>{minutesText(day.actual_minutes)}</b><span style={{height: `${Math.max(4, Math.min(100, day.planned_minutes ? day.actual_minutes * 100 / day.planned_minutes : 4))}%`}}/><small>{persianDate(day.date).split("،")[0]}</small></div>)}</div></section><section className="workspace-panel"><h2>پیشرفت بر اساس درس</h2>{progress.subjects.length ? <div className="workspace-subjects">{progress.subjects.map((subject) => <details key={subject.id}><summary><strong>{subject.name}</strong><span>برنامه مشاور: {minutesText(subject.planned_minutes)}</span><span>عملکرد: {minutesText(subject.actual_minutes)}</span><span>تست: {subject.actual_tests}</span><span>اجرا: {subject.completion_percent === null ? "—" : `${subject.completion_percent}٪`}</span></summary><div><p>تست برنامه‌ریزی‌شده: {subject.planned_tests} · غلط: {subject.wrong_tests ?? "ثبت نشده"}</p><p>کار تکمیل‌شده: {subject.completed} · ناقص/باقی‌مانده: {subject.incomplete} · فعالیت اضافه: {subject.extra_activities}</p>{progress.topic_repetition.filter((topic) => topic.subject_id === subject.id).map((topic) => <p key={topic.id}>مبحث «{topic.name}» — در برنامه مشاور: {topic.planned} بار · فعالیت واقعی دانش‌آموز: {topic.actual} بار</p>)}</div></details>)}</div> : <p className="workspace-empty-text">برای این بازه عملکردی ثبت نشده است.</p>}</section></div>;
}

function ProfileTab({ student, commitments }: { student: Student; commitments: Commitment[] }) {
  const weekdays = ["دوشنبه", "سه‌شنبه", "چهارشنبه", "پنجشنبه", "جمعه", "شنبه", "یکشنبه"];
  return <div className="workspace-stack"><section className="workspace-panel"><h2>اطلاعات تحصیلی</h2><dl className="workspace-profile"><div><dt>نام</dt><dd>{student.user.first_name} {student.user.last_name}</dd></div><div><dt>پایه</dt><dd>{student.grade_name || "ثبت نشده"}</dd></div><div><dt>رشته</dt><dd>{student.field_name || "ثبت نشده"}</dd></div><div><dt>مدرسه</dt><dd>{student.school_name || "ثبت نشده"}</dd></div></dl></section><section className="workspace-panel"><h2>تعهدهای ثابت</h2>{commitments.filter((item) => item.active).length ? <div className="workspace-commitments">{commitments.filter((item) => item.active).map((item) => <div key={item.id}><strong>{commitmentLabel[item.kind]} · {item.title}</strong><span>{weekdays[item.weekday]}، {timeText(item.start_time)} تا {timeText(item.end_time)}</span></div>)}</div> : <p className="workspace-empty-text">تعهد ثابتی ثبت نشده است.</p>}</section></div>;
}

export default function CounselorStudentDetail({ id }: { id: string }) {
  const { token } = useCounselor(); const [student, setStudent] = useState<Student | null>(null); const [commitments, setCommitments] = useState<Commitment[]>([]); const [plans, setPlans] = useState<Plan[]>([]); const [progress, setProgress] = useState<CounselorProgress | null>(null); const [tab, setTab] = useState<Tab>("overview"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { const [studentData, commitmentsData, plansData, progressData] = await Promise.all([api<Student>(`/students/${id}/`, token), allPages<Commitment>(`/planning/commitments/?student=${id}`, token), allPages<Plan>(`/planning/plans/?student=${id}`, token), api<CounselorProgress>(`/counselor/students/${id}/progress/`, token)]); setStudent(studentData); setCommitments(commitmentsData); setPlans(plansData); setProgress(progressData); }, [id, token]);
  useEffect(() => { void Promise.resolve().then(load).catch((reason) => setError(errorMessage(reason))).finally(() => setLoading(false)); }, [load]);
  const currentPlan = useMemo(() => { const today = tehranTodayIso(); return plans.find((plan) => plan.status === "PUBLISHED" && plan.start_date <= today && plan.end_date >= today); }, [plans]);
  if (loading) return <main className="planning-content"><p>در حال آماده‌سازی فضای دانش‌آموز…</p></main>;
  return <main className="planning-content student-workspace"><Link href="/counselor/students">← دانش‌آموزان</Link><p className="planning-error" role="alert">{error}</p>{student && progress && <><header className="workspace-header"><div><p className="workspace-eyebrow">فضای کار دانش‌آموز</p><h1>{student.user.first_name} {student.user.last_name}</h1><p>{student.grade_name || "پایه نامشخص"} · {student.field_name || "رشته نامشخص"}{student.school_name && ` · ${student.school_name}`}</p><small>{currentPlan ? `برنامه جاری: ${persianDate(currentPlan.start_date)} تا ${persianDate(currentPlan.end_date)} · منتشرشده` : plans.some((plan) => plan.status === "DRAFT") ? "برنامه جدید هنوز منتشر نشده" : "برای این دانش‌آموز هنوز برنامه فعالی ثبت نشده است."}</small></div><Link className="planning-primary" href={`/counselor/students/${id}/planning?new=1`}>+ نوشتن برنامه جدید</Link></header><nav className="workspace-tabs" aria-label="بخش‌های فضای دانش‌آموز">{tabs.map((item) => <button data-tab={item.id} className={tab === item.id ? "is-active" : ""} key={item.id} onClick={() => setTab(item.id)}>{item.label}</button>)}</nav>{tab === "overview" && <Overview id={id} progress={progress} currentPlan={currentPlan}/>} {tab === "plans" && <PlansTab id={id} plans={plans} progress={progress} token={token} reload={load}/>} {tab === "reports" && <ReportsTab id={id} token={token}/>} {tab === "progress" && <ProgressTab progress={progress}/>} {tab === "profile" && <ProfileTab student={student} commitments={commitments}/>}</>}</main>;
}
